### ISSUE TITLE
NOT working !

### ISSUE THREAD

**Issue by sah-anshu** [newfies-dialer/newfies-dialer#56]
(newfies-dialer) root@debian-s-1vcpu-2gb-blr1-01:/usr/share/newfies# pip --version
pip 9.0.3 from /usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages (python 2.7)
(newfies-dialer) root@debian-s-1vcpu-2gb-blr1-01:/usr/share/newfies# python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/sms/models/__init__.py", line 13, in <module>
    from message import Message
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/sms/models/message.py", line 7, in <module>
    import picklefield
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/picklefield/__init__.py", line 5, in <module>
    from picklefield.fields import PickledObjectField # reexport
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/picklefield/fields.py", line 79, in <module>
    class PickledObjectField(_get_subfield_superclass()):
  File "/usr/share/virtualenvs/newfies-dialer/local/lib/python2.7/site-packages/django/db/models/fields/subclassing.py", line 17, in __new__
    new_class = super(SubfieldBase, cls).__new__(cls, name, bases, attrs)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by areski** [comment]
Newfies-Dialer open source development was discontinued in 2015, but Newfies-Dialer continues to be developed as a commercial closed source product. See https://www.newfies-dialer.org

Newfies-Dialer is an auto-dialer supporting multi-tenancy and billing. You use your own VoIP carrier so there are potentially huge savings to be made when using Newfies-Dialer compared to competing products who insist on using their VoIP termination.

In recent years, there are countless improvements in terms of features, benefits and capacity of Newfies-Dialer. There is a list of changes at https://www.newfies-dialer.org/newfies-dialer-sms-voice-broadcasting-software-changelog/

**Comment by hoangddt** [comment]
@sah-anshu I am running into this problem. You can fix by uninstall `django-picklefield` and install it with this version `django-picklefield==0.3.2`

**Comment by sah-anshu** [comment]
Thanks buddy
